name: Deploy Frontend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: SSH and Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest frontend image from ECR..."

            # Login to AWS ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 454781577946.dkr.ecr.us-east-1.amazonaws.com

            echo "Cleaning up any container using port 80..."
            CONTAINER_ID=$(docker ps -q --filter "publish=80")
            if [ -n "$CONTAINER_ID" ]; then
              docker rm -f "$CONTAINER_ID"
            fi

            echo "Removing existing 'frontend' container if it exists..."
            docker rm -f frontend || true

            echo "Pulling latest image..."
            docker pull 454781577946.dkr.ecr.us-east-1.amazonaws.com/twxt/frontend:latest

            echo "Starting new frontend container..."
            docker run -d --name frontend -p 80:80 454781577946.dkr.ecr.us-east-1.amazonaws.com/twxt/frontend:latest

            echo "Frontend deployment complete."
